hl7au/au-fhir-base

examples/device-example0.xml, ig.json, pages/_includes/au-device-intro.md, pages/_includes/au-device-search.md, pages/_includes/au-device-summary.md, pages/_includes/profiles.md, resources/au-device.xml, resources/ig.xml
Hello Brett, 
As discussed, we have drafted a au-device profile consistent with other au profiles for your consideration. it has been added in  in ig.json, ig.xml, include files and a example file created.
It passed the testing against the schema and schematron and also has been processed with the IG Publisher. also note that this pull request has not been done via a GIT branch. 
Happy to discuss for any further changes.
Regards, 
Uday
=> Drafted au-device profile as discussed with Brett E

resources/au-device.xml
Hi Brett,
The Luhn check and 16 digit constraint has been included for PAI-D identifier.  Can you consider for merging.
Note- no changes have been made to markdown files. 
Cheers
David Mc
=> Feature - Added Luhn check and 16 digit constraint to the PAI-D identifier slice.  

examples/address-AustralianNoFixedAddressexample6.xml, examples/address-InternationalNoFixedAddressexample7.xml, examples/address-Maxexample1.xml, examples/address-Minexample0.xml, examples/address-StructuredAustralianAddressexample2.xml, examples/address-StructuredInternationalAddressexample3.xml, examples/address-UnstructuredAustralianAddressexample4.xml, examples/address-UnstructuredInternationalAddressexample5.xml, pages/_includes/au-address-intro.md, resources/au-address.xml, resources/ig.xml
1. Created new examples for Data Type Address, which includes min and max examples.
2. Corrected few typos.
3. Updated ig.xml and .md files accordingly.
=> Examples for Address Data Type :

resources/au-patient.xml, resources/structuredefinition-ihi-status.xml, resources/structuredefinition-indigenous-status.xml
Added fullstop to Au-patient in field of Patient.definition ie changed "Patient in Australian context" to "Patient in Australian context."
=> au-patient-added fullstop to Patient.definition.

pages/_includes/au-relatedperson-intro.md, pages/_includes/au-relatedperson-summary.md, resources/au-patient.xml, resources/au-relatedperson.xml
**Patient Profile:**
1. Fixed typos in DVA (color) and MRN (recrord) identifier descriptions in the profile.
**RelatedPerson profile:**
1. Found and changed patient references in the profile (intro.md).
2. Fixed typos in DVA (color) and MRN (recrord) identifier descriptions in the profile.
3. Included RelatedPerson.relationship binding in the profile using the agency valueset.
=> Fixes for Patient and RelatedPerson profiles:

pages/_includes/au-medication-intro.md, pages/_includes/au-medication-summary.md, resources/au-medication.xml
Hi Brett, 
Please accept the pull request which has following changes.
1. Optional and single package.content 
2. Optional and single package.batch
- Optional  MedicationBatchSerialNumber (as Extension)
FYI - this branch is applied on commit a972cae20b682835abd25175dcb91d029429923f
Thanks, 
Uday
=> au-medication - MedicationBatchSerialNumber (extension)

ig.json, pages/_includes/attester-related-party-intro.md, pages/_includes/ihi-status-intro.md, pages/_includes/indigenous-status-intro.md, pages/_includes/information-recipient-intro.md
Four extensions with changes to the example hyperlink text to be more consistent with the agreed conventions.
=> Extension narrative fixes

ig.json, pages/_includes/au-bodyheight-intro.md, pages/_includes/au-bodyheight-search.md, pages/_includes/au-bodyheight-summary.md, pages/_includes/au-bodyweight-intro.md, pages/_includes/au-bodyweight-search.md, pages/_includes/au-bodyweight-summary.md, pages/_includes/profiles.md, resources/au-bodyheight.xml, resources/au-bodyweight.xml, resources/ig.xml
au BodyHeight and BodyWeight profiles derived from STU3 VitalSigns BodyHeight and BodyWeight
=> Au bodyheightandweight

ig.json, pages/_includes/dispense-number-intro.md, pages/_includes/dispense-number-search.md, pages/_includes/dispense-number-summary.md, pages/_includes/extensions.md, resources/au-dispenserecord.xml, resources/ig.xml, resources/structuredefinition-dispense-number.xml
Hi Brett,
Please review and accept this pull request for the Dispense Number Extension.
Thanks heaps,
Vikas
=> Extension: Dispense number HL7 AU

examples/patient-example0.xml
Hi Brett, 
Please accept the pull request for a change to the birthDate value in Patient-example0 to 1985-10-14.
Thank you, 
Uday
=> Patient-example0 :: changed birthdate to be in the 80s

pages/_includes/composition-author-role-intro.md
Hi Brett,
Added the link to the related example for the Composition Author Role Extension. 
Submitted this pull request for your review.
Cheers,
Vikas
=> Updated Example Link(s) in the Composition Author Role Extension

resources/au-device.xml, resources/au-dispenserecord.xml, resources/au-healthcareservice.xml, resources/au-organisation.xml, resources/au-patient.xml, resources/au-practitioner.xml, resources/au-practitionerrole.xml, resources/au-prescription.xml, resources/au-relatedperson.xml
Hi Brett, please consider this pull request for new AllergyIntolerance artefacts.
- AllergyIntolerance profile with SNOMED bindings for 
-- `AllergyIntolerance.code`
-- `AllergyIntolerance.reaction.substance`
-- `AllergyIntolerance.reaction.manifestation`
- 2 aligned examples
- supporting updates in `ig.json` and `ig.xml`
=> AllergyIntolerance - profile and examples

examples/patient-example1.xml, examples/relatedperson-example1.xml, pages/_includes/au-relatedperson-intro.md, resources/ig.xml
Hi Brett,
Can you accept the 2 RelatedPerson examples:
1)  "Mary Smith as a carer";
2)  "Benedicte du Marche as a next of kin".
=> Related person examples 1)older person example 2) next of kin

resources/au-immunisation.xml
Hi Brett, please consider this PR that adds a slice on the Immunization.route element for a newly available NCTS terminology valueset using SNOMED.
(@dbojicic has done the work, I'm just the packager)
cheers
R
=> Immunization profile - added slice for route of admin for NCTS terminology 

examples/practitioner-example2.xml
=> Swap given and family names

pages/_includes/profiles.md, resources/au-address.xml
This pull request resolves the issue #150 . Fixing the invariants in Address profile.
=> Au address invariants

resources/au-immunisation.xml
Hi Brett,
Two slices have been added in the Immunization profile. 
One under the Immunization.explanation.reason and another under the Immunization.vaccinationProtocol.targetDisease
Please review and suggest if any changes need to be made.
Best Regards,
Vikas
=> au-immunisation: slices added

web-content/id/ahpra-registration-number/index.html
Hi Brett, this PR fixed issue #207 regarding adding information about what OID may be used in OID-based systems.
Note that there was only 1 change of 'substance', in that a new paragraph was added with 
```<p>In OID-based systems 1.2.36.1.2001.1005.56 may be used.</p>``` (on line 91). 
The other changes are all formatting - I added a couple of `<p>` tags around some of the content for readability, closed a meta tag as my editor was complaining, and the editor decided to do some nicer line wrapping etc. Sorry about the noise.
=> AHPRA namespace - add OID text

ig.json, pages/_includes/au-immunisationrecommendation-intro.md, pages/_includes/au-immunisationrecommendation-search.md, pages/_includes/au-immunisationrecommendation-summary.md, pages/_includes/profiles.md, resources/au-immunisationrecommendation.xml, resources/ig.xml
Hi Brett, 
I have created an AU profile for the ImmunizationRecommendation resource for your review and acceptance if it looks all good. 
Please let me know if you suggest improvments or changes. 
Thanks,
Vikas
=> New Profile: au immunisation recommendation

ig.json, pages/_includes/au-condition-intro.md, pages/_includes/extensions.md, pages/_includes/recorder-intro.md, pages/_includes/recorder-search.md, pages/_includes/recorder-summary.md, resources/au-condition.xml, resources/ig.xml, resources/structuredefinition-recorder.xml
Hi Brett, this new extension is a pre-adoption of the [R4 Condition.recorder](http://build.fhir.org/condition-definitions.html#Condition.recorder) element.
The build runs as expected and there are no new errors/warnings,
Rob
=> New extension - pre-adopt R4 Condition.recorder

pages/_includes/encounter-description-intro.md, resources/structuredefinition-encounter-description.xml
Hi Brett
This PR is a small narrative edit on the encounter description extension such that the term "short" has been removed, as descriptions can be quite long sometimes, eg in complex cases.
thank you
Rob
=> Condition description extension - narrative edits

ig.json, pages/_includes/au-encounter-intro.md, pages/_includes/au-encounter-search.md, pages/_includes/au-encounter-summary.md, pages/_includes/au-encounter-watermark.md, pages/_includes/profiles.md, resources/au-encounter.xml, resources/ig.xml
Hi Brett, this PR adds the Base Encounter profile as discussed recently.
Note that it has minimal content at this stage as other aspects are still underway (such as new extensions and terminology). This profile is the starting point for further additions once they become available.
=> New profile - AU Base Encounter (phase 1)

resources/au-encounter.xml
Hi Brett, this PR adds a slice on dischargeDisposition for Separation Mode along with binding to the new NCTS valueset.
Cheers
Rob
=> au-encounter - added slice for dischargeDisposition Separation Mode

resources/au-medication.xml
=> Meds repairs

pages/_includes/au-medication-intro.md, resources/au-medication.xml
Remove reference to PBS Sponsor extension
=>  Remove reference to PBS Sponsor extension from Medication

resources/au-norelevantfinding.xml
HL7 AU Assertion of No Relevant Finding :: added missing StructureDefinition Observation.definition.
=> Added missing Observation.definition

resources/au-relatedperson.xml
Hi Brett, 
I have changed relatedperson.communication valueset binding to the australian common languages in relatedPerson base profile.
Please accept the Pull Request.
Thank you.
Rodney
=> changed relatedperson.communication valueset binding to the australian common languages

pages/_includes/au-address-intro.md, pages/_includes/extensions.md, pages/_includes/profiles.md, resources/au-address.xml
Profile changes:
- au-address.xml : Forge changes ie adding <source>
Other changes associated with the review include:
1) au-address-intro.md: 
- updated STU3 references and links to R4
- made url text links into hyperlinks
2) extensions.md
- added "No Fixed Address" to the list of extensions
3) profiles.md
- added "AU Base Address" to the list of profiles
=> Updates related to AU Base Address

ig.json, pages/_includes/au-ihinumber-intro.md, pages/_includes/au-ihinumber-search.md, pages/_includes/au-ihinumber-summary.md, pages/_includes/profiles.md, resources/au-ihinumber.xml, resources/ig.xml
Hi Brett, please accept Pull Request for the IHI Identifier data type profile as recently discussed at the HL7 AU PA WG. This is in reference to GitHub issue #313
=> Add IHI Identifier data type profile

pages/_includes/au-dvanumber-intro.md, resources/au-dvanumber.xml
Added "healthcare" so that descriptions are "... in an Australian healthcare context."
Github issue: #384
=> DVA Number identifier profile - update description

resources/au-medicationrequest.xml
Hi Brett, please accept the pull request to update the MedicationRequest.reasonCode terminology binding as described in [MedicationRequest.reasonCode binding update #381](https://github.com/hl7au/au-fhir-base/issues/381).
=> AU Base Medication Request - updated reasonCode binding; related to #381

pages/_includes/profiles.md
Updated the link and the text now that the term "card" has been added
- the text was missing the term "card"
- the link was to the old file rather than the new one with the term "card"
=> Update profiles.md with "Medicare card number"

ig.json, pages/_includes/au-abnnumber-intro.md, pages/_includes/au-abnnumber-search.md, pages/_includes/au-abnnumber-summary.md, pages/_includes/profiles.md, resources/au-abnnumber.xml, resources/ig.xml
Good day Brett, 
Please review and accept the pull request for HL7AU ABN Identifier profile which is replicated from au-organisation profile from r4 repository.
This ABN Identifier dataType profile contains all the required .md files and other associated entries in .json and ig.xml files.
Thanks,
Uday
=> Australian Business Number :: Identifier dataType profile

ig.json, pages/_includes/au-employeenumber-intro.md, pages/_includes/au-employeenumber-search.md, pages/_includes/au-employeenumber-summary.md, pages/_includes/profiles.md, resources/au-employeenumber.xml, resources/ig.xml
Hello Brett, 
Please review and accept the pull request for identifier dataType profile of Employee Number and all its associated files for the build to successfully run.
Thanks, 
Uday
=> au-employeenumber :: identifier dataType profile of Employee Number

ig.json, pages/_includes/au-natasitenumber-intro.md, pages/_includes/au-natasitenumber-search.md, pages/_includes/au-natasitenumber-summary.md, pages/_includes/profiles.md, resources/au-natasitenumber.xml, resources/ig.xml
Hello Brett,
Please review and accept the pull request for identifier dataType profile of Nata Site Number and all its associated files for the build to successfully run.
Thanks,
Uday
=> au-natasitenumber :: identifier dataType profile of Nata Site Number

ig.json, pages/_includes/au-nataaccreditationnumber-intro.md, pages/_includes/au-nataaccreditationnumber-search.md, pages/_includes/au-nataaccreditationnumber-summary.md, pages/_includes/profiles.md, resources/au-nataaccreditationnumber.xml, resources/ig.xml
Hello Brett,
Please review and accept the pull request for identifier dataType profile of Nata Accreditation Number and all its associated files for the build to successfully run.
Thanks,
Uday
=> au-nataaccreditationnumber :: identifier dataType profile of Nata Accreditation Number

pages/_includes/profiles.md
Made list alphabetised, fixing of acronym usage, use of case, use of 'Australian' etc.
=> Bugfix/cifmm 3564 Fixes to profiles.md - alphabetise data type profiles

examples/organization-5-8631-1.xml, examples/organization-example3.xml, examples/organization-example4.xml, examples/organization-f799e349-0385-4fbc-a2aa-b5b50af957ea.xml, examples/practitioner-example0.xml, examples/practitioner-example1.xml, pages/_includes/au-organization-intro.md, pages/_includes/au-practitioner-intro.md, pages/_includes/profiles.md, resources/au-organization.xml
Fixed example QA errors: Removed text, removed CI assigned HI test data, added comments on ABN
AU Base Organization QA fix: add jurisdiction, update StructureDefinition.description to align to intro.md wording
AU Base Organization - improved intro.md: intro sentence inline with other PA profile updates, inclusion of Organization.type terminology
Relates to #333 
Fixes #359
=> AU Base Organization: QA update incl organization.type intro content

pages/_includes/au-healthcareservice-intro.md
Reinstate lost usage notes about HPI-O as a HealthcareService identifier
=> Added Usage Notes to au-healthcareservice-intro.md

examples/organization-example1.xml, examples/organization-example3.xml, examples/organization-f799e349-0385-4fbc-a2aa-b5b50af957ea.xml
Change Organization examples for follow guidance in profile
=> Change Organization examples for follow guidance in profile

resources/au-patient.xml
=> Added extended australianised value set to Patient.contact.relationship

resources/au-diagnostic-servicerequest.xml
=> AU Diagnostic Service Request - add extended australianised binding to reasonCode

ig.json, pages/_includes/au-localdispenseidentifier-intro.md, pages/_includes/au-localdispenseidentifier-search.md, pages/_includes/au-localprescriptionidentifier-intro.md, pages/_includes/au-localprescriptionidentifier-search.md, pages/_includes/profiles.md, resources/au-localdispenseidentifier.xml, resources/au-localprescriptionidentifier.xml, resources/ig.xml
Fixes https://github.com/hl7au/au-fhir-base/issues/525
Converted slice from [AU Base Medication Request](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationrequest.html) to a data type profile and drafted intro.md materials
Addresses the normative identifier slice issue https://github.com/hl7au/au-fhir-base/issues/533 by correcting the system value
Fixes https://github.com/hl7au/au-fhir-base/issues/526
Converted slice from [AU Base Medication Dispense](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationdispense.html) to a data type profile and drafted intro.md materials
Addresses the normative identifier slice issue https://github.com/hl7au/au-fhir-base/issues/534 by correcting the system value
=> Local Prescription Identifier and Local Dispense Identifier profiles

ig.json, pages/_includes/au-etpvendoridentifier-intro.md, pages/_includes/au-etpvendoridentifier-search.md, pages/_includes/profiles.md, resources/au-etpvendoridentifier.xml, resources/ig.xml
Fixes #524
Converted slice from [AU Base Medication Request](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationrequest.html) to a data type profile and drafted intro.md materials
Corrected the normative identifier slice issue https://github.com/hl7au/au-fhir-base/issues/533 by correcting the system value
=> ETP Vendor Identifier data type profile

examples/healthcareservice-example0.xml, examples/healthcareservice-example3.xml
Hello Brett,
Please review and accept the pull request where [use=WORK] has been added to healthcare service "example-0" and "example-3" examples of au-healthcareservice profile.
Thanks, 
Uday
=> au-healthcareservice :: Added [use=WORK] to healthcare service "example-0" and "example-3" 

examples/patient-example7.xml, resources/au-patient.xml
1)  Added descriptive content to AU Patient.identifier short to align with the short content of AU organization.short
2)  Added assigner.display values to patient-example7 to align with the MRN identifier profile requirements.
CIFMM-3589.
=> Minor updates to AU-Patient

examples/bundle-9309d080-4e97-11e9-8647-d663bd873d93.xml, examples/endpoint-example0.xml, examples/list-0ebc46a8-4ea8-11e9-8647-d663bd873d93.xml, examples/location-example0.xml, examples/patient-example0.xml, examples/patient-example1.xml, examples/patient-example2.xml, examples/patient-example3.xml, examples/patient-example4.xml, examples/patient-example5.xml, examples/patient-f12d073e-4e99-11e9-8647-d663bd873d93.xml, examples/practitioner-example0.xml, examples/relatedperson-example1.xml, examples/relatedperson-example2.xml, examples/relatedperson-example3.xml
Hi Brett, please consider accepting this Pull Request. All examples (except for practitionerrole-example0 through to practitionerrole-example4) were checked to make sure the telecom values and identifier values including namespaces are ok. Several examples were subject to some small changes.
=> Feature/sraig 209 hl7 au review all examples for identifier telecom values. GitHub Issue #503

pages/_includes/au-allergyintolerance-intro.md
Good day Brett, 
Please review and accept pull request which is about informative material regarding the extensions where the following text has been added in intro.md file.
No extensions are used in this profile.
Kind Regards, 
Uday
=> au-allergyintolerance: Informative material about whether extension are provided or otherwise

pages/_includes/au-diagnostic-observation-intro.md, pages/_includes/au-diagnostic-servicerequest-intro.md, pages/_includes/au-diagnosticreport-intro.md
Hi Brett, 
Please review and accept the pull request which is an update AU Base HL7 AU intro.md for AU Base Diagnostic Report, AU Diagnostic Observation, 
and AU Diagnostic Service Request to actually link to the Evaluation Procedure value set.
Thanks, 
Uday
=> Evaluation Procedure value set : Update to intro.md files 

pages/_includes/au-location-intro.md
Hi Brett, 
Just updated the Usage Notes in the au-location profile to include the type='VI' along with  physicalType=’vi'  
Please review and accept the request if all good. 
Thanks.
=> SRAIG-279 - Updated the usage notes. Examples already found up to date.

resources/structuredefinition-information-recipient.xml
Fixes #537
Fixes QA errors related to composition-multiple-information-recipients-and-author-role.xml.
=> Information recipient extention - added fixed url.

pages/_includes/au-bodystructure-intro.md, pages/_includes/au-specimen-intro.md, resources/au-specimen.xml
- Removed erroneous binding.descriptions, and updated Specimen.short
- Styling fixes to intro.md
- Fixed page title
Also found added a fix to intro.md for AU Body Structure to fix title and add in the std phrasing for a Base profile
=> AU Specimen QA fixes

ignoreWarnings.txt, pages/_includes/au-immunization-intro.md, resources/au-immunization.xml
Partial fix for FHIRIG-161 
Fixes #672 & similar Fix for 'route'
=> Ballot fix : Issue 672 - Changes to Immunisation site ValueSet binding Postiion

pages/_includes/au-estimateddateofdelivery-intro.md, resources/au-estimateddateofdelivery.xml, resources/au-gravidity.xml, resources/au-lastmenstrualperiod.xml, resources/au-parity.xml, resources/au-smokingstatus.xml
The five Draft 0 profiles of AU Smoking Status, AU Estimated Time of Delivery, AU Gravidity, AU Last Menstral Period and AU Parity, had their StructureDefinition files updated so the slices would function as desired and some tidy up of short and definitions.
=> HL7 AU ballot fixes technical design issues for 5 level 0 profiles

resources/au-immunization.xml
The short of au-immunization.performer:approvedBy.actor was changed from "Approving practitioner" to "Approver"
Addresses #692
=> Ballot Fix: AU Base Immunisation - update short of .performer:approvedBy.actor

pages/_includes/au-bloodpressure-intro.md, pages/_includes/au-bmi-intro.md, pages/_includes/au-bodyheight-intro.md, pages/_includes/au-bodytemp-intro.md, pages/_includes/au-headcircum-intro.md, pages/_includes/au-heartrate-intro.md, pages/_includes/au-oxygensat-intro.md, pages/_includes/au-resprate-intro.md, pages/_includes/au-vitalspanel-intro.md, resources/au-bloodpressure.xml, resources/au-bmi.xml, resources/au-bodyheight.xml, resources/au-bodytemp.xml, resources/au-bodyweight.xml, resources/au-headcircum.xml, resources/au-heartrate.xml, resources/au-oxygensat.xml, resources/au-resprate.xml, resources/au-vitalspanel.xml
Small wording improvements to the vital signs profiles to profile description and root element definition.
=> Vital signs informative changes

input/ig.xml
Adds fmm-definition param to local definition
=> Localised fmm link

input/resources/au-address.xml, input/resources/au-ahpraregistrationnumber.xml, input/resources/au-bodystructure.xml, input/resources/au-deliverypointidentifier.xml, input/resources/au-diagnosticresult.xml, input/resources/au-hpii.xml, input/resources/au-hpio.xml, input/resources/au-ihi.xml, input/resources/au-imagingresult.xml, input/resources/au-nationalprovideridentifieratorganisation.xml, input/resources/au-paididentifier.xml, input/resources/au-paioidentifier.xml, input/resources/au-pathologyresult.xml, input/resources/au-patient.xml, input/resources/au-practitioner.xml, input/resources/structuredefinition-identifier-routability.xml
In StructureDefinitions it adds a condition attribute to the ElementDefinition of all elements affected by an invariant added in AU Base. Raised as ballot issue [FHIRIG-213](https://jira.hl7australia.com/browse/FHIRIG-213) on 4.1.0-ballot..
=> Add ElementDefinition.condition in StructureDefinitions

input/resources/structuredefinition-veteran-status.xml
Remove max occurrence constraint on Australian Veteran Status extension definition. 
Fixes #803.
=> Remove max occurrence constraint on AU Veteran Status extension definition

buildv.bat, input/ig.xml, package-list.json
Changes for AU Base snapshot 4.1.2 for Connectathon.
=> 4.1.2 preview

input/ig.xml
Change version number following a snapshot release in 4.2.x sequence
=> Change version number

ig.ini
Set template dependency to 0.7.0
=> Set template dependency to 0.7.0

input/resources/searchparameter-gender-identity.xml
This PR provides a fix for https://jira.hl7.org/browse/FHIR-46079. 
Changes: 
- fixed gender-identity expression
=> Fix gender-identity SearchParameter expression (https://jira.hl7.org/browse/FHIR-46079)

input/resources/searchparameter-encounter-discharge-disposition.xml, input/resources/searchparameter-gender-identity.xml, input/resources/searchparameter-indigenous-status.xml
fix for https://jira.hl7.org/browse/FHIR-46073
=> FHIR-46073: Change to FMM1 and status=active

input/pagecontent/changes.md, input/resources/au-pathologyresult.xml
Fixes https://jira.hl7.org/browse/FHIR-46080
=> AU Base PathologyResult: Add additionalBindings to Observation.code from guidance

input/pagecontent/changes.md, input/resources/structuredefinition-identifier-routability.xml
This PR provides fix for FHIR-46213. 
Changes:
- changed inv-idrout-0 FHIRPath expression to remove all warnings (Option 2 in https://jira.hl7.org/browse/FHIR-46213)
- updated Change log
=> Fix invariant FHIRPath expression (FHIR-46213)

input/intro-notes/StructureDefinition-au-medicationrequest-intro.md
Removed sex/gender guidance note that was incorrectly included.
=> Remove incorrect sex/gender guidance note

_updatePublisher.sh, input/intro-notes/StructureDefinition-au-patient-intro.md, input/intro-notes/StructureDefinition-au-practitioner-intro.md, input/intro-notes/StructureDefinition-au-relatedperson-intro.md, input/pagecontent/changes.md, input/resources/au-patient.xml, input/resources/au-practitioner.xml, input/resources/au-relatedperson.xml, input/resources/valueset-rsg-source-document-jurisdiction.xml, input/resources/valueset-rsg-source-document-type.xml, input/resources/valueset-rsg-type.xml
Fixes for https://jira.hl7.org/browse/FHIR-46106
=> Approved updates for FHIR-46106

input/pagecontent/changes.md, input/resources/valueset-rsg-type.xml
for https://jira.hl7.org/browse/FHIR-46544
add SNOMED CT AU code 1515311000168102|Biological sex at birth|
=> Change to Valueset-rsg-type

input/resources/au-medicationstatement.xml
This PR provides fix for [FHIR-46998](https://jira.hl7.org/browse/FHIR-46998).
=> Add Medication reference (FHIR-46998)

input/pagecontent/changes.md, input/resources/au-localorderidentifier.xml
Fix for [FHIR-47188](https://jira.hl7.org/browse/FHIR-47188)
* Remove min constraint
* Change log entry
=> Remove minimum constraint on Identifier.assigner in AU Local Order Identifier (FHIR-47188)

input/resources/au-imagingresult.xml, input/resources/au-medicationdispense.xml
Fix for [FHIR-46999](https://jira.hl7.org/browse/FHIR-46999)
* Remove target reference in MedicationDispense.authorizingPrescription 
Fix for [FHIR-47118](https://jira.hl7.org/browse/FHIR-47118)
* Change description for AU Base Diagnostic Imaging Result from path to imaging example.
=> Remove target reference MedicationDispense.authorizingPrescription; change AU Base DI Result description (FHIR-46999, FHIR-47118)

input/pagecontent/changes.md
Updated change message for [FHIR-46544](https://jira.hl7.org/browse/FHIR-46544)
=> Updated change message for FHIR-46544 (#898)

input/resources/valueset-mims.xml
=> Added NCTS profile to MIMS ValueSet

input/pagecontent/future.md
This PR provides fix for https://jira.hl7.org/browse/FHIR-47165.
=> Future of AU Base page changes to add Future FHIR Versions and Future Candidate Requirements Under Consideration sections (FHIR-47165)

input/examples/immunization-example1.xml, input/examples/immunization-example2.xml
Approved TCs for https://jira.hl7.org/browse/FHIR-48605 and https://jira.hl7.org/browse/FHIR-48608
=> Vaccine Example1 and Example2 technical correction 

input/pagecontent/changes.md, input/pagecontent/generalguidance.md, package-feed.xml
Fixes https://jira.hl7.org/browse/FHIR-48307 and replaces [#Pr866](https://github.com/hl7au/au-fhir-base/pull/866)
- added guidance and examples 
- added to change log
=> FHIR-48307 Added Guidance on SNOMED CT

.github/workflows/profile_tag_trigger_publication.yml, input/examples/patient-example9.xml, input/pagecontent/changes.md, input/resources/au-patient.xml, input/resources/au-patientinternalidentifier.xml
HL7 JIRA Tracker: [FHIR-48671](https://jira.hl7.org/browse/FHIR-48671)
- Created profile for AU Patient Internal Identifier 
- Added profile to changes.md 
- Added example of patient with PI assigned by a medical centre (example9)
=> AU Patient internal identifier profile

input/resources/au-patientinternalidentifier.xml, input/resources/au-relatedperson.xml
- Updated cardinality of Identifier.system to 1..1
- changed ambiguous word "system" to "application" in a number of places.
=> Patient Individual Identifier profile - Post WG discussion fixes

input/intro-notes/StructureDefinition-au-patientinternalidentifier-intro.md
Added a PII notes section that explains why it is different to an MRN
=> patient identifier profile notes

input/pagecontent/changes.md, input/resources/au-healthcareservice.xml
Changes for [FHIR-46322](https://jira.hl7.org/browse/FHIR-46322) additional binding. 
Examples already exists for use of this element.
=> HealthcareService communication binding (FHIR-46322)

input/pagecontent/changes.md, input/resources/au-allergyintolerance.xml, input/resources/au-bodystructure.xml, input/resources/au-diagnosticreport.xml, input/resources/au-healthcareservice.xml, input/resources/au-immunization.xml, input/resources/au-medicationadministration.xml, input/resources/au-medicationdispense.xml, input/resources/au-medicationrequest.xml, input/resources/au-medicationstatement.xml, input/resources/au-organization.xml, input/resources/au-practitionerrole.xml, input/resources/au-relatedperson.xml, input/resources/au-servicerequest.xml
Changes to implement AU FHIR artefact policy to retain FHIR resource spelling in profile name and title ([FHIR-46685](https://jira.hl7.org/browse/FHIR-46685)):
- [AU Base HealthcareService](https://build.fhir.org/ig/hl7au/au-fhir-base/branches/ft_46685_profiletitlepolicy/StructureDefinition-au-healthcareservice.html)
- [AU Base RelatedPerson](https://build.fhir.org/ig/hl7au/au-fhir-base/branches/ft_46685_profiletitlepolicy/StructureDefinition-au-relatedperson.html)
- [AU Base PractitionerRole](https://build.fhir.org/ig/hl7au/au-fhir-base/branches/ft_46685_profiletitlepolicy/StructureDefinition-au-practitionerrole.html)
- [AU Base AllergyIntolerance](https://build.fhir.org/ig/hl7au/au-fhir-base/branches/ft_46685_profiletitlepolicy/StructureDefinition-au-allergyintolerance.html)
- [AU Base …
=> FHIR-46685 Changes to apply profile title & name policy update

input/resources/au-pi.xml
Updated resource description, post review feedback
=> Post review feedback on Patient Internal Identifier

input/pagecontent/changes.md, input/resources/au-encounter.xml
Fix for https://jira.hl7.org/browse/FHIR-50996:
- changed AU Base Encounter
- changed changes.md
=> Add Encounter.reasonCode binding (FHIR-50996)

input/ig.xml, input/intro-notes/StructureDefinition-au-coverage-intro.md, input/pagecontent/changes.md, input/pagecontent/terminology.md, input/resources/au-coverage.xml, input/resources/codesystem-au-coverage-type.xml, input/resources/codesystem-coverage-type.xml, input/resources/valueset-au-coverage-type-extended.xml
- Changes to CodeSystem and Valueset id, url, name to align with AU Base conventions.
=> Post review updates

input/ig.xml, input/pagecontent/changes.md, input/pagecontent/terminology.md, input/resources/codesystem-communicationrequest-reason.xml
Fixes [FHIR-51348](https://jira.hl7.org/browse/FHIR-51348). 
Changes to add code system:
- new code system
- change log
- terminology page
- ig.xml
=> Add Communication Request Reason code system (FHIR-51348)

input/ig.xml, input/pagecontent/changes.md, input/pagecontent/terminology.md, input/resources/codesystem-task-business-status.xml, input/resources/codesystem-task-businessstatus.xml
Fixes [FHIR-51350](https://jira.hl7.org/browse/FHIR-51350). 
Changes to add code system:
- new code system
- change log
- terminology page
- ig.xml
=> Add Task Business Status code system (FHIR-51350)

input/resources/au-coverage.xml, input/resources/codesystem-communicationrequest-reason.xml, input/resources/codesystem-resource-tag.xml, input/resources/codesystem-task-business-status.xml, input/resources/searchparameter-servicerequest-supporting-info.xml
Fixes for https://jira.hl7.org/browse/FHIR-51550 and https://jira.hl7.org/browse/FHIR-51549
Changes to move from DRAFT 0 to AFMM 1: 
- ServiceRequestSupportingInfo
- Resource Tag
- Communication Request Reason
- Task Business Status
- AU Base Coverage
=> Move artefacts from DRAFT 0  to AFMM 1 (FHIR-51549 and FHIR-51550)

input/pagecontent/changes.md
Update change log after 6.0.0-ballot release
=> Update change log after release
