hl7au/au-fhir-base

pages/_includes/au-patient-intro.md
pages/_includes/au-patient-summary.md
resources/au-patient.xml

Hi Brett, 
The Agency has added the STU3 standard extension for [birthTime](http://hl7.org/fhir/STU3/extension-patient-birthtime.html) into our profile derived from the HL7 AU patient profile. Recently though I understand that you have indicated an interest to have this extension in the HL7 AU patient profile, which would then be inherited by the Agency derived profile.
This pull request modifies the base au-patient profile to include this extension. It has been given the following attributes:
- cardinality: 0..1
- URL as the STU3 URL
- and various strings such as slice name, short description, definition, comment and reason for inclusion.
The au-patient markdown files have also been updated to align with the above changes, which builds successfully with the IG publisher.

Feature - patient birthtime extension added

---

resources/au-device.xml

Add into the Device profile slice for the PAI-D identifier a fixed value for the identifier.type.coding as has been done with the Organisation HPI-O slice.
The fixed value details (as found in the HL7 V2 Table 0203 - Identifier Type (AU Extended) code system) are:
System: http://hl7.org.au/fhir/v2/0203
Code: NDI
Display: National Device Identifier
(Note that the example device instance already uses the above values.) 
Addresses Issue #3

Feature - Device.identifier PAI-D slice, add type.coding for "NDI"

---

examples/patient-BirthDateAccuracyIndicatorAAAexample0.xml
examples/patient-BirthDateAccuracyIndicatorAAUexample1.xml
examples/patient-BirthDateAccuracyIndicatorUAAexample2.xml
examples/patient-BirthDateAccuracyIndicatorUEAexample3.xml
examples/patient-BirthDateAccuracyIndicatorUUUexample4.xml
ig.json
pages/_includes/patient-birth-date-accuracy-indicator-intro.md
pages/_includes/patient-birth-date-accuracy-indicator-search.md
pages/_includes/patient-birth-date-accuracy-indicator-summary.md
resources/au-patient.xml
resources/ig.xml
resources/patient-birth-date-accuracy-indicator.xml

Hello Brett, 
As requested please find the pull request for Patient Birth Date Accuracy Indicator extension for au-patient profile which works with FHIR IG Publisher with no issues.
Note that below three constraints FHIR Path expressions are still under construction (TBD)-
- Where the accuracy indicator states that a day is estimated or accurate, the string representation of the date would not have "00" for the day.
- Where the accuracy indicator states that a month is estimated or accurate, the string representation of the date would not have "00" for the month.
- Where the accuracy indicator states that a year is estimated or accurate, the string representation of the date would not have "0000" for the year.
Also note the the NCTS ValueSet …

Patient Birth Date Accuracy Indicator extension for au-patient

---

examples/practitioner-example0.xml
pages/_includes/au-practitioner-intro.md
resources/au-practitioner.xml
resources/codesystem-au-hl7v2-0203.xml

Hi Brett, this PR adds the AHPRA registration number value format constraint, as discussed.
There are a few supporting changes as well:
- updated the extended v2-0203 table entry to align with other identifier entries (add "Registration Number")
- updated the `Practitioner.identifier.type.text` fixed value to align with the above
- added an identifier node with an AHPRA example to the example practitioner file
- updated the narrative intro of the practitioner profile with AHPRA content
Note that the IG builds as expected with the IG publisher with no errors generated for the above content.
Refer to issue   #11

Feature - added AHPRA number constraint

---

resources/ihi-record-status.xml
resources/ihi-status.xml
resources/indigenous-status.xml

The two IHI-related extensions ([IHI status](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-ihi-status.html) and [IHI record status](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-ihi-record-status.html)) were missing the `Extension.url` node - these were added.
As Forge now automatically prepopulates this node, presumably this was missing as an earlier version of Forge (that created these extensions) did not automate this. Or the extension was created manually outside of Forge. Note that as this node is autopopulated in Forge, there was no frontend mechanism in Forge to make this setting; therefore the changes were made directly to the xml.
Another extension ([indigenous-status](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-indigenous-st …

Added Extension.url to IHI-related extensions

---

pages/_includes/ihi-record-status-intro.md
pages/_includes/ihi-status-intro.md

The 2 IHI-related extensions ([ihi-record-status](https://github.com/hl7au/au-fhir-base/blob/master/resources/ihi-record-status.xml#L30) and [ihi-status](https://github.com/hl7au/au-fhir-base/blob/master/resources/ihi-status.xml#L29)) have a context of use of 'Identifier' set in their respective profiles. 
In order to make this clearer This content was added to the intro narrative markdown pages for the 2 extensions.
The content builds as expected with the IG publisher and there are no new QA report errors or warnings.

Added context of use to narrative of 2 IHI-related extensions

---

pages/_includes/close-the-gap-registration-intro.md
pages/_includes/close-the-gap-registration-summary.md
resources/structuredefinition-close-the-gap-registration.xml

Hi Brett; this PR makes some minor changes to the narrative content for the CTG extension:
- added a description in the intro markdown page
- updated the summary markdown file to mention the datatype boolean
- minor updates to the profile's description, purpose and extension definition
The updated content builds as expected with the IG publisher with no new QA report errors/warnings.

Close the gap extension - narrative updates

---

examples/addressAustralianNoFixedAddressexample6.xml
examples/addressInternationalNoFixedAddressexample7.xml
pages/_includes/no-fixed-address-intro.md
pages/_includes/no-fixed-address-summary.md
resources/structuredefinition-no-fixed-address.xml

Hi Brett; this PR makes some minor changes to the narrative content for the no fixed address extension:
- corrected a typo in the extension intro markdown narrative
- added 2 links to the intro markdown file for the 2 examples demonstrating no fixed address
- reworded the 2 example narratives
- updated the example for international no fixed address (typo and couple of other minor edits)
- added the datatype (boolean) to the extension summary
- reworded the profile's description and purpose
The updated content builds as expected with the IG publisher with no new QA report errors/warnings.
Note - we had some discussion whether it was worthwhile adding some narrative guidance for using this flag; ie only can assert positively that there is no fixed address. Rather than suggesting some …

No fixed address extension - narrative updates

---

examples/patient-example1.xml
pages/_includes/extensions.md
pages/_includes/ihi-record-status-intro.md
pages/_includes/ihi-record-status-summary.md
pages/_includes/ihi-status-intro.md
pages/_includes/ihi-status-summary.md
resources/structuredefinition-date-accuracy-indicator.xml
resources/structuredefinition-ihi-record-status.xml
resources/structuredefinition-ihi-status.xml

Hi Brett; this Pull Request makes very minor changes to the narrative content for the Date Accuracy Indicator, IHI Status and IHI Record Status extensions:
Minor updates to the profile's description, purpose, extension definition and intro.md files.
The updated content builds as expected with the IG publisher with no new QA report errors/warnings.

Date Accuracy Indicator, IHI Status and IHI Record Status - narrative updates.

---

pages/_includes/indigenous-status-intro.md
resources/structuredefinition-indigenous-status.xml

Hi Brett, this PR includes a couple of minor updates to the narrative content of the Indigenous Status extension, including:
- adding links for the 2 patient examples in the extension's intro markdown file
- fixed typo in profile's description
- replaced profile's purpose text
- fully spelled-out 'NHDD' in extension's definition
The content builds as expected with the IG publisher and there are no new QA report errors/warnings.
Thanks

Indigenous Status extension - narrative updates

---

ig.json
pages/_includes/composition-author-role-intro.md
pages/_includes/composition-author-role-search.md
pages/_includes/composition-author-role-summary.md
pages/_includes/extensions.md
resources/ig.xml
resources/structuredefinition-composition-author-role.xml

Hi Brett,
Please accept the pull request for composition-author-role.
**Summary of changes:**
**Extension Cardinality**:: 0..*
**Name**:: CompositionAuthorRole
**Title**:: Authoring PractitionerRole
**Short Description**:: Authoring PractitionerRole
**ContextOfUse**:: Composition
**Description**:: A practitioner role that authored this composition. This is not to be confused with who typed in the information.
**Extension, profiled**::
- **url**:: 1..1 "http://hl7.org.au/fhir/StructureDefinition/composition-author-role"
- **valueReference**:: 1..1 Reference (PractitionerRole)
Thanks,
Vikas

Extension :: composition-author-role

---

examples/composition-different-authors.xml
examples/composition-multiple-information-recipients-and-author-role.xml
pages/_includes/au-composition-intro.md
resources/ig.xml

Hi Brett, 
Can you please accept the pull request which consists examples for au-composition with below details.
1. First example with some sections have a different section-author to the Composition.author
2. Second with a composition-author-role, and multiple information-recipients of different resource type
Thanks and Kind Regards, 
Uday

au-composition :: examples to display Information Recipient, Composition Author role and Section Author

---

examples/composition-WithAttesterRelatedParty.xml
examples/composition-example0.xml
pages/_includes/au-composition-intro.md
resources/ig.xml

Hi Brett,
Can you please accept the pull request which consists of the example being updated after a number of internal reviews.
This is an example where the Related Person is the Attester Party.
There are a number of changes made.
- example's id is changed.
- example file renamed as the id was changed. 
- Description about the example in the intro file is updated. 
- ig.xml file is updated as the example file was renamed. 
- the manual entry for the narrative has been removed from the example and now defaults to the generated narrative.
- author and attester are now the same person.
- dates have been updated to represent the chronological order.
- some elements which were immaterial to the example presented has been removed. 
- the section has been added and the narrative of the section …

au-composition :: examples to display related person as attester party (updated)

---

resources/au-organisation.xml

The [current definition of the root element Organization](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-organisation-definitions.html#Organization) currently reads:
> Australian realm Organisation profile often healthcare or related service provision.
Which doesn't seem quite right, particularly the last half. The Agency is working towards a revised Participant Data Specification, as derived from the HL7 AU profiles, that uses this content. We are therefore looking to have this content improved and are proposing a simplification to just:
> Australian realm Organisation
This PR makes this change for the following 2 elements in the profile:
- StructureDefinition.description (to be "_Australian realm Organisation profile_")
- root element Organization.definition (to be …

au-organisation profile - simplified narratives

---

resources/au-practitionerrole.xml

The [current definition of the PractitionerRole.identifier element](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole-definitions.html#PractitionerRole.identifier) reads:
> business identifiers for practitioner in a role
Proposing minor edits to add first letter capitalisation and a period at the end.
> Business identifiers for practitioner in a role.

au-practitionerrole - minor revision to identifier definition

---

ig.json

Hi Brett, with one of the [new commits made to master](https://github.com/hl7au/au-fhir-base/commit/30c87b322f548f4af978a4458a3c7c0b9758a444#diff-fa7d071b576c819977fd9c91648449a4), to introduce element hyperlinks to their detailed descriptions via changes to the ig.json, there are a number of typos. Some of the links are "...definition.html" not "...definition**s**.html".
Consequently, their profile detailed description tabs are giving 404 error.
This commit fixes the typo and the links were tested via a new IG build and the detailed description tabs are now working as expected.

ig.json typo fix

---

pages/_includes/composition-author-role-intro.md
pages/_includes/information-recipient-intro.md

Corrected a broken link in Information recipient Extension that uses the same example.

Added link to Author Role Extension example in introduction.

---

resources/au-medicationstatement.xml

Hello Brett, 
Please accept the following changes to au-medicationstatement profile -
**reasonNotTaken**
1. coding slice, unordered, open, on value:system
2. 0..1 slice coding (SNOMED CT) with required binding to https://healthterminologies.gov.au/fhir/ValueSet/medication-reason-not-taken-1
3. slice name is snomedReasonNotTaken
4. slice description is Reason Not Taken (SNOMED CT)
**reasonCode**
1. coding slice, unordered, open, on value:system
2. 0..1 slice coding (SNOMED CT) with required binding to https://healthterminologies.gov.au/fhir/ValueSet/medication-reason-taken-1
3. slice name is snomedReasonCode
4. slice description is Reason For Medication (SNOMED CT)
**dosage** typed to AU Base Dosage
Resolved FHIR schema error with the location if <short> element at "Medication Detail" …

au-medicationstatement :: Slices for reasonNotTaken and reasonCode and AU Base Dosage reference

---

resources/au-patient.xml
resources/au-practitioner.xml

As agreed in the HL7 AU PAWG 29-8-2018 (refer [minutes](https://confluence.hl7australia.com/display/PA/2018-08-29+Minutes)), the following elements are to have a new terminology binding to a NCTS valueset:
- `Patient.communication.language`
- `Practitioner.communication`
The new binding extends the current STU3 binding to [Common Languages (bcp.47)](http://hl7.org/fhir/valueset-languages.html) to include a number of Indigenous Australian languages; and is https://healthterminologies.gov.au/fhir/ValueSet/common-languages-australia-1

Added common Australian languages valueset to patient communication & practitioner communication

---

pages/_includes/au-practitionerrole-summary.md
resources/au-practitionerrole.xml

PractitionerRole.location cardinality constraint of 0..1 was removed to revert to the default 0..*.
This was the agreement at the HL7 AU working group meetings held 13/9/2018.
Also updated various narratives to align with the multiplicity.
(Note that this element in this commit still references the AU Base Location profile rather than the STU3 location. My intent here is to create a targeted change specifically for cardinality & the type change will be the subject of the next PR).

au-practitionerrole - reverted location cardinality to default

---

examples/practitioner-example1.xml

Hi Brett, 
Please accept the pull request to change the text value of AHPRA qualification in au-practitioner
<text value="Diagnostic and Interventional Radiologist"/>
<text value="Diagnostic radiology"/>
Kind Regards,
Uday

au-practitioner :: Radiologist example :: Changed the text value of AHPRA qualification to "Diagnostic radiology"

---

pages/_includes/au-practitionerrole-summary.md
resources/au-practitionerrole.xml

The constraint of typing the following elements in the PractitionerRole profile to AU Base profiles has been removed:
- PractitionerRole.practitioner
- PractitionerRole.organization
- PractitionerRole.location
- PractitionerRole.healthcareService

au-practitionerrole - reverted type references

---

resources/au-practitioner.xml

The constraint of typing the following elements in the Practitioner profile to AU Base profiles has been removed:
- Practitioner.qualification.issuer
- Practitioner.qualification:ahpraRegistration.issuer

au-practitioner - reverted type references

---

pages/_includes/au-patient-summary.md
resources/au-patient.xml

The constraint of typing the following elements in the Patient profile to AU Base profiles has been removed:
- Patient.contact.organization
- Patient.generalPractitioner (as Practitioner and Organization)
- Patient.managingOrganization
- Patient.link.other (as Patient and RelatedPerson)

au-patient - reverted type references

---

resources/au-organisation.xml

The constraint of typing the following element in the Organization profile to a AU Base profile has been removed:
- Organization.partOf
The result of which is that it references its STU3 counterpart instead. This was the agreement at the HL7 AU working group meetings held 13/9/2018.

au-organisation - reverted type references

---

resources/au-healthcareservice.xml

The constraint of typing the following elements in the HealthcareService profile to AU Base profiles has been removed:
- HealthcareService.providedBy
- HealthcareService.location
- HealthcareService.coverageArea

au-healthcareservice - reverted type references

---

pages/_includes/au-device-summary.md
resources/au-device.xml

The constraint of typing the following elements in the Device profile to AU Base profiles has been removed:
- Device.patient
- Device.owner
- Device.location

au-device - reverted type references

---

pages/_includes/au-relatedperson-summary.md
resources/au-relatedperson.xml

The constraint of typing the following element in the RelatedPerson profile to a AU Base profile has been removed:
- RelatedPerson.patient
The result of which is that it references its STU3 counterpart instead. This was the agreement at the HL7 AU working group meetings held 13/9/2018.

au-relatedperson - reverted type references

---

resources/au-location.xml

The constraint of typing the following elements in the Location profile to AU Base profiles has been removed:
- Location.managingOrganization
- Location.partOf

au-location - reverted type references

---

pages/_includes/au-allergyintolerance-summary.md
resources/au-allergyintolerance.xml

The constraint of typing the following elements in the AllergyIntolerance profile to AU Base profiles has been removed:
- AllergyIntolerance.patient
- AllergyIntolerance.recorder (as patient, practitioner or relatedperson)
- AllergyIntolerance.asserter (as patient, practitioner or relatedperson)

au-allergyintolerance - reverted type references

---

pages/_includes/au-condition-summary.md
resources/au-condition.xml

The constraint of typing the following elements in the Condition profile to AU Base profiles has been removed:
- Condition.subject (as patient)
- Condition.asserter (as patient, practitioner or relatedperson)

au-condition - reverted type references

---

pages/_includes/au-bodysite-summary.md
resources/au-bodysite.xml

The constraint of typing the following elements in the Bodysite profile to AU Base profiles has been removed:
- BodySite.patient

au-bodysite - reverted type references

---

web-content/id/abn/index.html
web-content/id/acn/index.html

Hi Brett - this PR adds info for OID based systems regarding which OIDs to use for ABN and ACN respectively.
Note that the hl7.org.au endpoints for each of these have a short description but this is not present in the files I have added the OID content into.

HL7.org.au namespaces ACN & ABN - added OID info

---

resources/au-medication.xml

Added parent elements for Medication.form and Medication.package so that constraints on their respective children appear in the generated differential table.
Fixes #246

au-medication bugfix - added missing parent elements

---

resources/au-allergyintolerance.xml

Moved extension elements to be directly following the root element rather than interspersed between other elements.
Fixes #247

au-allergyintolerance bugfix - reordered extension elements

---

resources/au-patient.xml
resources/au-practitioner.xml
resources/structuredefinition-healthcareservice-communication.xml

Hi Brett, this PR updates the version number of the common-lanuages-australia binding to v2.
URL updated in the 3 profiles where this binding is present:
- [au-patient profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html)
- [au-practitioner profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html)
- [Healthcare Service Communication extension](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-healthcareservice-communication.html)
URLs changed to 
https://healthterminologies.gov.au/fhir/ValueSet/common-languages-australia-2
The v2 valueset has been implemented by NCTS, and from that perspective the PR is ready to be merged in. However, a [zulip thread](https://chat.fhir.org/#narrow/stream/179173-australia …

Updated version of common-languages-australia valueset to v2

---

pages/_includes/au-medlist-intro.md
resources/au-medlist.xml

Hi Brett, this PR is for the AU Base Medicine List profile to allow Assertion of No Relevant Finding. Some guidance text has also been added for when the assertion of no relevant finding would be used. 
Note this is the set of changes authored by Dushi which she has spoken with you about.

AU Base Medicine List - added allowance for Assertion of No Relevant Finding

---

resources/au-medlist.xml

The FHIRPath error crashes the IG publisher when an example uses the profile.

repair invalid FHIRPath in au-medlist invariant

---

pages/_includes/associated-healthcareservice-summary.md
resources/structuredefinition-associated-healthcareservice.xml

Hello Brett, 
Please accept the pull request to change the valueReference of HL7AU extension for associated health service to STU3 HealthCare Service.
Thanks, 
Uday

HL7 AU extension associated healthcare service - fixed the valueReference to STU3 Healthcare Service

---

ig.json
pages/_includes/extensions.md
pages/_includes/performer-party-intro.md
pages/_includes/performer-party-search.md
resources/au-medication.xml
resources/ig.xml
resources/structuredefinition-performer-party.xml

Hi Brett, 
Please accept the pull request in regards to a new extension for Performer Party with below brief description.
- url with fixed value "http://hl7.org.au/fhir/StructureDefinition/performer-party"
- Short: "Performing practitioner role or care team"
- definition: "The performing party (care team or practitioner role) associated with the service, e.g the diagnostic service responsible for issuing the report or the desired performer for doing the requested service."
- 1..1 valueReference  Reference (PractitionerRole | CareTeam)
Thanks, 
Uday

HL7 AU Performer Party - proposed extension

---

ig.json
pages/_includes/au-diagnosticobservation-intro.md
pages/_includes/au-diagnosticobservation-search.md
pages/_includes/au-diagnosticobservation-summary.md
pages/_includes/au-diagnosticobservation-watermark.md
pages/_includes/profiles.md
resources/au-diagnosticobservation.xml
resources/core-extensions/extension-body-site-instance.xml
resources/ig.xml

Hi Brett, 
New profile for Diagnostic Observation added with its usual complement of supporting file and file changes.
A copy of the STU3 body-site-instance extension has been added into the resources/core-extensions folder, in line with other extensions.
Note there is a pending change for this profile to add another slice on Observation.code.coding for Standards for Pathology Informatics in Australia - Test Result (LOINC) - this is awaiting NCTS development.
Cheers
Rob

Add new profile - AU Base Diagnostic Observation (phase 1)

---

ig.json
pages/_includes/au-diagnosticprocedurerequest-intro.md
pages/_includes/au-diagnosticprocedurerequest-search.md
pages/_includes/au-diagnosticprocedurerequest-summary.md
pages/_includes/au-diagnosticprocedurerequest-watermark.md
pages/_includes/profiles.md
resources/au-diagnosticprocedurerequest.xml
resources/core-extensions/extension-procedurerequest-targetbodysite.xml
resources/core-extensions/extension-serviceRequest-patientInstruction.xml
resources/ig.xml
resources/structuredefinition-au-diagnosticprocedurerequest.xml

Hi Brett,
New profile for Diagnostic Procedure Request added with its usual complement of supporting file and file changes.
Note there are pending changes for this profile to:
1) Add another slice on ProcedureRequest.code.coding for Standards for Pathology Informatics in Australia - Test Result (LOINC) - this is awaiting NCTS development.
2) Add R4 pre-adopt element instruction - "patientInstruction" - refer to https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Syntax.20for.20canonical.20pre-adoption.20convention
3) Include NCTS terminology for "reasonCode" is about to be released.
Cheers
D Mc

Add new profile -Au Base Diagnostic ProcedureRequest phase 1

---

examples/practitioner-example0.xml
examples/practitioner-example1.xml
examples/practitioner-example2.xml
examples/practitioner-example3.xml
pages/_includes/au-practitioner-intro.md
resources/au-practitioner.xml

Hi Brett, this PR proposes a number of improvements related to the AU Base Practitioner profile:
- updated `StructureDefinition.date` to be recent (rather than 2017)
- corrected the `StructureDefinition.contact.telecom.value` with the correct URL
- updated all invariant keys to align with the convention (as recently discussed with Richard)
- simplified and standardised the invariant descriptions (eg "_HPI-I shall be an exactly 16 digit number_" changed to "_HPI-I shall be 16 digits_" etc)
- dot point re 'Medicare Prescriber Number - removed the 2nd link to a AIHW website with what looks like a different concept (at least from the perspective of the format anyway). This is associated with the recently added issue #304.
- dot point re AHPRA added into the list of identifiers and added a …

AU Base Practitioner - improvements to profile and examples

---

resources/au-practitioner.xml

Hello Brett, 
Please accept the pull request where a spelling mistake has been identified when deriving the profile in definition value which has "Providier" instead of "Provider".
Kind Regards, 
Uday

au-practitioner :: Fixed a spelling mistake in definition which has "Providier" instead of "Provider"

---

resources/au-address.xml

Hello Brett, 
In a recent assessment of deriving r4 au-address profile, we identified that the invariants in the profile were not triggering in negative and positive scenario testing. hence please accept this pull request which has been created to address those concerns.
Below is the summary of changes to the profile.
- invariant 0,1,2 now have relative paths
- moved invariant 3 to address level
- corrected the syntax of invariant 3 to remove the country = 'AU' as there is already a fixed value constraint for country = 'AU'
- corrected the regular expression for invariant 3 to have ('^[0-9]{4}$')
Kind Regards, 
Uday

au-address :: Invariants Fix

---

examples/practitionerrole-example1.xml
resources/au-healthcareservice.xml
resources/au-practitionerrole.xml
resources/codesystem-au-hl7v2-0203.xml
resources/codesystem-au-hl7v2-0443.xml
resources/valueset-au-hl7v2-0203.xml
resources/valueset-au-hl7v2-0443.xml
resources/valueset-snomed-practitioner-specialties.xml

Improvements to au-practitionerole.xml include:
- moving inv-npio-0 from element to the parent to make it function as required.
- update version 1.0.0 to 2.0.0
- update contact.telcom.value to "http://hl7.org.au/fhir"
- Forge changes including adding <source> and removal of redundant extensions.
practitionertrole-example1.mxl:
- added example NPIO value
- updated telecom.value to match the organization
- deleted <availableTime> content as it is represented in another example.
Other changes related to AU Base Practitioner Role profile include:
- codesystem-au-hl7v2-0203.xml; codesystem-au-hl7v2-0443.xml; valueset-au-hl7v2-0203.xml; valueset-au-hl7v2-0443.xml:  updated the contact.telcom.value to "http://hl7.org.au/fhir"
- valueset-snomed-practitioner-specialties.xml :  updated the …

AU Base Practitioner Role improvements

---

resources/ig.xml

This PR addresses and eliminates 18 QA errors on the ig.xml - and fixes issue #325
The changes are:
- 12 QA errors related to elements being out of order - specifically, the `resource.name` and `resource.description` elements should come after their associated `resource.reference` elements. These were reordered.
- Removed 3 extensions (2x `igpublisher-folder-resource` and 1 `igpublisher-folder-pages`), all of which had strings values of absolute folder paths of a specific PC. As a result, 6 QA errors were eliminated.
- and a handful of empty lines / whitespaces were also removed just as a tidy up
A local rebuild after these changes (with IG Publisher v1.0.62) has no errors on the ig.xml and otherwise seems to render content as expected.

Implementation guide QA fixes

---

ig.json
pages/_includes/au-dvanumber-intro.md
pages/_includes/au-dvanumber-search.md
pages/_includes/au-dvanumber-summary.md
pages/_includes/profiles.md
resources/au-dvanumber.xml
resources/ig.xml

As recently discussed at the HL7 AU PA WG - this is the second identifier profile created.
As discussed this profile has not been hooked up to a "parent" profile eg au-patient.
Refer to HL7 AU Confluence page au-fhir-base - creation of Identifier datatype profiles.
See also Practitioner, PractitionerRole, Organization, HealthcareService DataType profiles #313

Add DVA Number identifier profile

---

resources/au-patient.xml
resources/au-relatedperson.xml

The Medicare Number identifier slices for both [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) and [AU Base RelatedPerson](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-relatedperson.html) were updated to remove the cardinality constraint on their respective `period` and `period.end` elements. 
That is, from `1..1` both were reverted to the default cardinality of `0..1`
Their short names were retained , as is.
This was discussed as desirable in a PAWG late last year; and also note that the same model was used in the recently developed [Medicare Number Identifier profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicarenumber.html).
Even though the profiles will likely move away from the …

Base Patient and Base RelatedPerson - relax MedicareNumber constraint

---

ig.json
pages/_includes/au-hpiinumber-intro.md
pages/_includes/au-hpiinumber-search.md
pages/_includes/profiles.md
resources/au-hpiinumber.xml
resources/ig.xml

As recently discussed at the HL7 AU PA WG - another identifier profile has been created.
As discussed this profile has not been hooked up to a "parent" profile, e.g.  au-patient.
Refer to HL7 AU Confluence page [au-fhir-base - creation of Identifier datatype profiles](https://confluence.hl7australia.com/display/PA/au-fhir-base+-+creation+of+Identifier+datatype+profiles).
See also [Practitioner, PractitionerRole, Organization, HealthcareService DataType profiles #313](https://github.com/hl7au/au-fhir-base/issues/313).

Add HPI-I Number identifier profile #313 

---

resources/au-practitionerrole.xml

Hello Brett, 
This pull request address the GitHub request (https://github.com/hl7au/au-fhir-base/issues/348) which is in regards to having an invariant to validate the value element of NPIO slice.
"value.matches('^(800361)([0-9]{10})(@)(800362)([0-9]{10})$')"
Thanks, 
Uday

au-practitionerrole :: An invariant performing the validation for @value for the NPIO slice

---

ig.json
pages/_includes/au-patient-intro.md
pages/_includes/extensions.md
pages/_includes/year-of-arrival-intro.md
pages/_includes/year-of-arrival-search.md
resources/au-patient.xml
resources/ig.xml
resources/structuredefinition-year-of-arrival.xml

Adding draft extension for capturing the year of arrival of a patient, to support collection of CALD data.
This extension has a basic structure to just capture the year value as a date, and has been included in the AU Base Patient profile as 0..1.
The intent is to use a local build of this IG to demonstrate the extension at the next PAWG.
Addresses #357

Extension year of arrival - for PAWG discussion

---

resources/au-diagnosticreport.xml

DiagnosticReport.performer now reverts to the default 0..* as is found in the DiagnosticReport resource.
Addresses Github ticket: #411

AU Base Diagnostic Report - removed 0..1 constraint on performer

---

resources/au-bodystructure.xml

Hi Brett, updating the existing valueset binding strength of BodyStructure.morphology to 'preferred'.
Addresses #409

AU Base BodyStucture Profile - changed morphology binding to preferred

---

resources/au-norelevantfinding.xml

Hi Brett; this PR fixes issue #449 
Looks like the URL wasn't updated when it was migrated from STU3.
Therefore, no urgency.
Thanks

AU Assertion of No Relevant Finding - fixed codesystem URL for v3/ActCode

---

examples/practitioner-example0.xml
pages/_includes/au-healthcareservice-intro.md
pages/_includes/au-location-intro.md
pages/_includes/au-patient-intro.md
pages/_includes/au-practitioner-intro.md
pages/_includes/au-practitionerrole-intro.md
pages/_includes/au-relatedperson-intro.md
resources/au-healthcareservice.xml
resources/au-location.xml
resources/au-patient.xml
resources/au-practitioner.xml
resources/au-practitionerrole.xml
resources/au-relatedperson.xml

Updated HL7 AU Base PA Profiles except Organisation and encounter.
Changes made include:
A) Intro.md:
1)  update of introductory sentences
2)  Remolval of "Profile" from title"
B)StructureDefinition changes:
1)  Align definition to opening sentence in intro.md
2) Added jurisdiction
3) updated FHIR version to 4.0.1
C)  Updated Practitioner-example0

Update HL7 AU Base PA profiles except Organistation

---

resources/codesystem-au-hl7v2-0203.xml

The following codes have been added to the code system 
[http://terminology.hl7.org.au/CodeSystem/v2-0203](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-hl7v2-0203.html):
Code | Display | Definition
-- | -- | --
NATAA | National Association of Testing Authority Accreditation Number | A National Association of Testing Authorities (NATA) accreditation number associated with an accredited facility. A NATA accreditation number is associated with an organisation.
NATAS | National Association of Testing Authority Site Number | A National Association of Testing Authorities (NATA) site number associated with an accredited facility. A NATA site number represents a specific location associated with an accredited facility, i.e. an organisation with a NATA accredication number.
LSPN | …

Added codes - HL7 table 0203 code for NATA identifiers & LSPN

---

resources/codesystem-au-hl7v2-0203.xml

In  HL7 0203 code system (AU extended) the typo in the NATAS description has been corrected from "accredication" to "accreditation".

Typo correction

---

examples/condition-example0.xml

For example [Condition-example0](http://build.fhir.org/ig/hl7au/au-fhir-base/Condition-example0.html), this PR fixes QA errors re `Condition.clinicalStatus` and `Condition.verificationStatus` - both needed to be converted to have the CodeableConcept structure.
As a by product of this change, the generated narrative for this example then populated their respective values, which were previously missing.
Fixes #475

Fix Condition example QA errors

---

resources/au-allergyintolerance.xml
resources/au-condition.xml
resources/au-dosage.xml
resources/au-immunization.xml
resources/au-medication.xml
resources/au-medicationadministration.xml
resources/au-medicationdispense.xml
resources/au-medicationrequest.xml
resources/au-medicationstatement.xml
resources/au-medlist.xml
resources/au-norelevantfinding.xml
resources/codesystem-gtin.xml
resources/codesystem-medication-type.xml
resources/codesystem-mims.xml
resources/codesystem-pbs-item.xml
resources/structuredefinition-change-description.xml
resources/structuredefinition-dispense-number.xml
resources/structuredefinition-medication-brand-name.xml
resources/structuredefinition-medication-generic-name.xml
resources/structuredefinition-medication-long-term.xml
resources/structuredefinition-medication-type.xml
resources/structuredefinition-minimum-interval-between-repeats.xml
resources/structuredefinition-subsidised-concurrent-supply.xml
resources/valueset-amt-mp-codes.xml
resources/valueset-grounds-for-concurrent-supply.xml
resources/valueset-gtin.xml
resources/valueset-mims.xml
resources/valueset-pbs-item.xml

Includes fixes to add jurisdiction declaration and update date and contact details; mostly related to Medications profiles & related terminology.
Fixes #484.

QA fixes - add missing jurisdiction for #484 & other Metadata fixes 

---

resources/au-organization.xml

Relates to #334; update base extensible binding for Organization.contact.purpose in AU Base Organization to be the new Contact Purpose Extended value set which includes additional values to support extended contact purpose.

AU Base Organization - update binding of contact.purpose to AU value set

---

resources/au-healthcareservice.xml
resources/au-practitionerrole.xml

Updated terminology bindings in HL7 AU Base Healthcare Service and Practitioner Role.
Terminology bindings changed from HL7 bindings to NCTS bindings.
- Binding on PractitionerRole.specialty changed to https://healthterminologies.gov.au/fhir/ValueSet/clinical-specialty-1 ValueSet
- Binding on HealthcareService.type changed to https://healthterminologies.gov.au/fhir/ValueSet/service-type-1  ValueSet
- Binding on HealthcareService.specialty changed to https://healthterminologies.gov.au/fhir/ValueSet/clinical-specialty-1 ValueSet

Updated terminology bindings for AU Base Healthcare Service and AU Base Practitioner Role

---

examples/medicationstatement-MedicationStatementexample0.xml
examples/medicationstatement-MedicationStatementexample1.xml
examples/medicationstatement-MedicationStatementexample2.xml
resources/structuredefinition-medication-type.xml

Fixes #479.
Related to #482, #481
Changes to MedicationType extension StructureDefinition context declaration to be of type fhirPath.
Changes to MedicationStatement examples 
- medicationstatement-MedicationStatementexample0.xml
- medicationstatement-MedicationStatementexample1.xml
- medicationstatement-MedicationStatementexample2.xml
to fix the QA errors related to unknown elements and elements out of order.

Updated MedicationType extension and MedicationStatement examples

---

resources/au-immunization.xml

Fixes https://github.com/hl7au/au-fhir-base/issues/486.
Changes made:
- Removed Immunization.protocolApplied.targetDisease.coding:targetDiseaseNoInformation slice as targetDisease is optional in R4 Immunization. The slice was introduced in STU3 profile of Immunization where targetDisease was mandatory to provide guidance for systems that may not have this information.
- Removed Immunization.protocolApplied.targetDisease.coding:snomedTargetDisease slice and placed the binding on the targetDisease element with the strength of 'preferred'.

AU Base Immunisation targetDisease - removed slices and placed terminology binding on the element

---

examples/list-0ebc46a8-4ea8-11e9-8647-d663bd873d93.xml
examples/list-e0a6c4a6-4e97-11e9-8647-d663bd873d93.xml

Fixes https://github.com/hl7au/au-fhir-base/issues/483.
Made following changes:
- In list-0ebc46a8-4ea8-11e9-8647-d663bd873d93.xml
corrected order of subject element in contained MedicationStatement examples
corrected Encounter.priority code system value to R4; previously example included STU3 value
- In list-e0a6c4a6-4e97-11e9-8647-d663bd873d93.xml
removed the author-role extension fragment and included source element instead. The extension was needed in STU3 where source did not allow for PractitionerRole which is not the case anymore.

AU Medicines List examples QA fixes

---

resources/structuredefinition-medication-type.xml

Removed the slicing definition from the extension StructureDefinition to fix the qa error:
Profile http://hl7.org/fhir/StructureDefinition/ElementDefinition, Element 'StructureDefinition.differential.element[2].slicing.rules': minimum required = 1, but only found 0

Medication Type QA fix

---

resources/codesystem-au-hl7v2-0203.xml

With exception of recently added LSPN, CSP, CAEI, NATAA, NATAS - improved the code definitions by:
- grammatically correct sentences
- corrected spelling typos
- introduced context and meaning within an Australian setting
Additionally removed the CodeSystem.text element - as agreed out of recent work on the Contact Purpose terminology this element should by default not be present.
Closes #365

hl7 v2 table 0203 extended improve definitions

---

examples/practitionerrole-example0.xml
examples/practitionerrole-example1.xml
examples/practitionerrole-example2.xml
examples/practitionerrole-example3.xml
examples/practitionerrole-example4.xml

Use preferred values for code and specialty, use example values for telecom and identifier.

Correct errors in PractitionerRole examples

---

resources/au-patient.xml

Hi,
The two tags (min and max) in the au-patient have been removed as they were causing qa errors.
They seem to be redundant.
Please review and accept as required.
Thanks,
Vikas

removing redundant min max tags from au-patient

---

pages/_includes/au-address-intro.md
pages/_includes/profiles.md
resources/au-address.xml

1) au-address title and name changed to "Australian Address" and "AustralianAddress" respectively. This is to align with the HL7 AU conventions - where au-address is not a base profile and should not be name as a base profile.
2) Updated FHIR Version to 4.0.1.

Corrected AU Base address profile title & name & updated FHIR version

---

pages/_includes/au-allergyintolerance-intro.md
resources/au-allergyintolerance.xml

1) A previous version of Forge had added <extension /> content to 3 sections of code.  This content is not needed and the current version of Forge removes this content.
2)  The constraint "inv-ait-0" is now obsolete as it involved an extension added for STU3, but this extension is not required and is not present in R4; hence the constraint needs to be deleted.  Subsequently the content in the intro.md describing the constraint needs to be deleted.
CIFMM-3592.

Removed erroneous content & deleted redundant invariant

---

examples/allergyintolerance-example1.xml
resources/ig.xml

The link to the example was broken due to the file not being listed in the ig.xml. But when it was, there were then 6 errors that needing fixing.
1. Added allergyintolerance-example1 example into ig.xml
1. Example: allergyintolerance-example1
- corrected element name (changed 'assertedDate' to 'recordedDate')
- corrected structure of clinicalStatus and verificationStatus
Fixes #564

AU Base Allergy Intolerance - fixed broken example link

---

pages/_includes/au-allergyintolerance-intro.md
resources/au-allergyintolerance.xml

1)  The terminology binding on AllergyIntollerance.code was updated from https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-1 to https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 with the deletion of text int he intro.md referring to the impending update.
2) The short for AllergyIntollerance.reaction was deleted as the existing short of "Reaction details" was only present to circumvent a previous IG Publisher problem which has since been resolved.

Minor updates to AU AllergyIntolerance profile

---

pages/_includes/au-sexassignedatbirth-intro.md
resources/au-sexassignedatbirth.xml

Hello, please accept this PR with proposed changes to the existing draft profile:
* Changed SNOMED code from 268476009 to 1515311000168102 |Biological sex at birth| and defined a mandatory SNOMED slice as the current design is failing validation. I was unable to confirm though that this is the intent of the original design (that an instance is always expected to include a SNOMED code and could optionally include LOINC code 76689-9).
* Removed constraints on the status fixed value of 'final' and effective[x] minimum cardinality as the AU profile should leave these open and available to be constrained by specific implementation requirements
* Added terminology binding to value[x]; it is bound to  [Biological Sex](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/biological- …

AU Sex Assigned At Birth changes

---

examples/relatedperson-example3.xml
resources/au-relatedperson.xml

Hello Brett, 
Please review and accept the pull request regarding the following changes to au-relatedperson and its example-3.
- Adding identifier and display for RelatedPerson.patient element of "RelatedPerson-example3" example to show the Implementers that not only reference can be used to mention the patient but also identifier and display can be used
- Edited the definition RelatedPerson.communication.language to have "A language which can be used to communicate with about the patient's health." it will look like below :
"A language which can be used to communicate with about the patient's health. The ISO-639-1 alpha 2 code in lower case for the language, optionally followed by a hyphen and the ISO-3166-1 alpha 2 code for the region in upper case; e.g. "en" for English, or "en-US" for …

au-relatedperson ::   Edits to short descriptions, definitions and example

---

examples/bundle-9309d080-4e97-11e9-8647-d663bd873d93.xml
examples/medication-BrandProductwithBatchDetails0.xml
examples/medication-BrandedPack0.xml
examples/medication-BrandedPack1.xml
examples/medication-BrandedPackSingleActiveIngredient0.xml
examples/medication-CombinationPackage0.xml
examples/medication-FourOrMoreActiveIngredientsProduct0.xml
examples/medication-GenericPack0.xml
examples/medication-MedicationDoseBased.xml
examples/medication-TwoActiveIngredientsProduct0.xml
examples/medication-UnbrandedProduct0.xml
examples/medication-UnbrandedProduct1.xml
examples/medication-UnbrandedProduct2.xml
examples/medicationstatement-MedicationStatementexample0.xml
examples/medicationstatement-MedicationStatementexample1.xml
examples/medicationstatement-MedicationStatementexample2.xml

Fixes #604
This reduces the error count from 90 to 33.
Note that there are still other errors still apparent in medication examples that remain to be fixed.

Fixed multiple medication examples with R4 codesystem URL.

---

examples/composition-different-authors.xml
examples/composition-example0.xml
resources/ig.xml

Added references to two examples to ig
Within examples removed redundant extensions and added relevant element to capture information contained in extension.
Reduces Build QA errors by 2. 
Addresses #536

Fixing 2 composition hyperlink examples

---

ignoreWarnings.txt
pages/_includes/au-allergyintolerance-intro.md
resources/au-allergyintolerance.xml

Fixes #572 AllergyIntolerance: Binding to exposureRoute is 'example'.
Updated date and version, removed binding.description - not necessary and is repeat of element description.
Additionally style fixes to intro material:
- Examples heading style fix
- Standard intro statement added
Added warning for exposureRoute element to ignoreWarnings.txt so that it builds clean (current agreement from PA WG to do this while getting snapshot ready for ballot)

AU Base AllergyIntolerance QA fix incl exposureRoute binding

---

examples/composition-multiple-information-recipients.xml
pages/_includes/address-identifier-intro.md
pages/_includes/associated-healthcareservice-intro.md
pages/_includes/attester-related-party-intro.md
pages/_includes/au-assigningauthority-intro.md
pages/_includes/au-composition-intro.md
pages/_includes/au-receivingapplication-intro.md
pages/_includes/au-receivingfacility-intro.md
pages/_includes/au-timezone-intro.md
pages/_includes/author-related-person-intro.md
pages/_includes/change-description-intro.md
pages/_includes/contact-purpose-intro.md
pages/_includes/encounter-description-intro.md
pages/_includes/encryption-certificate-pem-x509-intro.md
pages/_includes/extensions.md
pages/_includes/identifier-routability-intro.md
pages/_includes/information-recipient-intro.md
pages/_includes/no-fixed-address-intro.md
resources/ig.xml
resources/structuredefinition-au-assigningauthority.xml
resources/structuredefinition-au-receivingapplication.xml
resources/structuredefinition-au-receivingfacility.xml
resources/structuredefinition-encryption-certificate-pem-x509.xml

Fixes #615, Fixes #614, Fixes #613, Fixes #596.
Fix style and wording in extension.md and intro.md for extensions that aren't subject of forthcoming PRs (medication, patient, ahpra).

Bugfix/QA Fix v2 extensions missing urls plus style QA fixes

---

pages/_includes/au-norelevantfinding-intro.md
resources/au-norelevantfinding.xml

Fixes #616 Assertion of No Relevant Finding - needs refactoring to remove slicing and erroneous prohibition:
- Removed slicing on value
- Removed prohibition on dataAbsentValue
- Improved wording around value
Intro QA fixes to align with current style including fix title, add headings, move content into Usage Notes

AU Assertion No Relevant Finding QA fixes

---

pages/_includes/au-medicationstatement-intro.md
resources/au-medicationstatement.xml

MedicationStatement
- removed unnecessary shorts and definitions; kept the long-term extension short as it is more explanatory than what would come from the extension
- added MedicationStatement.medicationCodeableConcept.text short - this now matches other meds profiles, and might make Usage Notes easier to understand
- updated date and version
intro.md
- added two standard AU Base profiles paragraphs (2nd and 3rd)
- hyperlinked extensions to their definitions
- moved content from Medication Reference/Coding into the Usage Notes -
usage notes content now pretty much matches AU Base MedicationDispense Usage Notes now with small tweaks for MedicationStatement
- changed Examples heading style

AU Base Medication Statement QA fixes

---

examples/address-example1.xml
pages/_includes/au-address-intro.md
resources/au-address.xml

- updated description to align with standardised patterns
- removed unnecessary definitions
- improved short names
- version patch bump & date updated
- removed 'profile' from heading
- expanded introductory text to align to standard descriptions and added a purpose statement with text from the usage notes. Removed mention of unstructured address given that the profile is pitched at best practice guidance
- identifiers section - improved introductory sentence to include mention of the extension and removed the extension itself as a dot point from the list of identifiers
- extensions section - added 'core' to the potentially useful list
- usage notes - most content moved into introduction or removed as unnecessary
- examples section - heading changed to standard 4# and added a 4th example …

Australian Address profile QA fixes

---

pages/_includes/au-location-intro.md
resources/codesystem-au-v2-0203.xml

Location usage notes typo fixes #648
Corrected usage notes from "mobile='kind'" to "mode=’kind’".
IdentifierTypeAU NOI definition typo fixes #654
Corrected 'a repository' to 'an organisation'.

QA typo fixes on Location & IdentifierTypeAU

---

examples/norelevantfinding-example1.xml
examples/norelevantfinding-example3.xml
examples/patient-example7.xml
examples/servicerequest-hepatitis-b-antibody.xml
ignoreWarnings.txt
pages/_includes/au-localorderidentifier-intro.md

Fix for FHIRIG-148: SCT code 401179006 changed to 1234401000168109 to conform to profile binding.
Fix for FHIRIG-149: SCT code 1200661000168109 changed to 1234391000168107 to conform to profile binding.
Fix for FHIRIG-150: Added missing 2nd-level 'example' subdomain to the example private health insurer namespace.

Ballot fix: minor example fixes

---

resources/au-immunization.xml

Slice on snomedRoute now has coding.system as 1..1 and fixed value of http://snomed.info/sct
Error re 'Could not match discriminator' has been eliminated.
Addresses HL7AU Ballot ticket [FHIRIG-158](https://jira.hl7australia.com/browse/FHIRIG-158)

Ballot fix: AU Base Immunisation profile- add constraints on route

---

pages/_includes/au-estimateddateofdelivery-intro.md
pages/_includes/au-gravidity-intro.md
pages/_includes/au-lastmenstrualperiod-intro.md
pages/_includes/au-parity-intro.md
pages/_includes/au-smokingstatus-intro.md
resources/au-estimateddateofdelivery.xml
resources/au-gravidity.xml
resources/au-lastmenstrualperiod.xml
resources/au-parity.xml
resources/au-smokingstatus.xml

The meta data of 5 profiles were missing content according tho the AU Base meta data conventions at:
https://github.com/hl7au/au-fhir-base/wiki/HL7-AU-Conventions:-profile-and-extension-metadata.
Fixes issues in:
[FHIRIG-162](https://jira.hl7australia.com/browse/FHIRIG-162), [FHIRIG-160](https://jira.hl7australia.com/browse/FHIRIG-160), [FHIRIG-168](https://jira.hl7australia.com/browse/FHIRIG-168), [FHIRIG-166](https://jira.hl7australia.com/browse/FHIRIG-166) & [FHIRIG-164](https://jira.hl7australia.com/browse/FHIRIG-164)

Ballot Fix: Fixes of meta data & intro.md's for 5 profiles

---

resources/au-medication.xml

Changes included in this PR:  
- removed Medication.ingredient.item[x] slicing, and and placed preferred binding to AMT Medicinal Product and Substances value set on Medication.ingredient.item[x].
Fixes #674. 
- removed erroneous StructureDefinition.extension.

Updates to AU Base Medication profile

---

resources/au-medicationadministration.xml
resources/au-medicationdispense.xml
resources/au-medicationrequest.xml
resources/au-medicationstatement.xml

medicationReference typing has been removed from these 4 profiles from R4 HL7AU medication to R4 Base medication
- AU Base Medication Administration
- AU Base Medication Dispense
- AU Base Medication Request
- AU Base Medication Statement
Addresses ballot comment [FHIRIG-183](https://jira.hl7australia.com/browse/FHIRIG-183)

Ballot fix: remove medicationReference typing from 4 medication profiles from R4 HL7AU medication to R4 Base medication

---

pages/_includes/au-medicationrequest-intro.md

A Conversion note was added to au-medicationrequest-intro.md to show that the extension Minimal Interval Between Repeats is no longer needed in R4.
Issue is related to #688.

AU Base Ballot: Added Conversion note to au-medicationrequest-intro.md

---

resources/structuredefinition-subsidised-concurrent-supply.xml

Subsidised Concurrent Supply extension has a new value setet that has been implemented in the NCTS - https://healthterminologies.gov.au/fhir/ValueSet/concurrent-supply-grounds-1. 
Therefore swapped the valueset binding to this NCTS value set. 
This change addresses HL7AU ballot comment https://jira.hl7australia.com/browse/FHIRIG-169

Ballot Fix: Subsidised Concurrent Supply extension has a new value set

---

resources/au-sexassignedatbirth.xml

The LOINC copyright statement has been updated to align with the statement from LOINC (Regenstrief) at https://loinc.org/kb/license/ point 10.1 and the [HL7 AU profile conventions](https://github.com/hl7au/au-fhir-base/wiki/HL7-AU-Conventions:-profile-and-extension-metadata).
Closes #711

 au sex assigned at birth update copyright notice for LOINC

---

examples/immunization-example3.xml
ig.json
ignoreWarnings.txt
pages/_includes/au-immunization-intro.md
pages/_includes/extensions.md
pages/_includes/vaccine-serial-number-intro.md
pages/_includes/vaccine-serial-number-search.md
pages/_includes/vaccine-serial-number-summary.md
pages/_includes/vaccine-serial-number-watermark.md
resources/ig.xml
resources/structuredefinition-vaccine-serial-number.xml

Addition of vaccine vial serial number extension in support of government reporting requirements for COVID-19 vaccinations. Closes #712
Closes https://github.com/AuDigitalHealth/ci-fhir-r4/issues/144

Submission of Vaccine (Vial) Serial Number extension

---

resources/structuredefinition-encryption-certificate-pem-x509.xml
resources/structuredefinition-ethnicity.xml
resources/structuredefinition-medication-strength.xml

There were some inconsistent status allocation wrt the FMM level there include :
1) Draft 0 profiles with status = "active" of: 
- structuredefinition-medication-strength
- structuredefinition-ethnicity
(where all other Draft 0 artifacts have status = "draft")
2) FMM level 3 profile with status = "draft" of:
- structuredefinition-encryption-certificate-pem-x509
(where all other FMM 3 artifacts have status = "active")
Profiles with FMM of "Draft 0" were changed to have a status ="draft" and;
profiles with FMM 3 were changed to have a status of "active".
Fixes #708

HL7 AU Ballot Fixes:  inconsistent status wrt fmm level

---

pages/_includes/au-gestationalage-intro.md
pages/_includes/profiles.md
resources/au-gestationalage.xml

Completes the set of changes needed to be a complete profile at DRAFT 0 including copyright and other metadata, meaningful descriptions including shorts, slicenames etc, fixes technical problems with the slicicing.
Addresses issues for Gestational age profile noted in https://github.com/hl7au/au-fhir-base/issues/667.

Gestational age QA fixes

---

ig.json
ignoreWarnings.txt
pages/_includes/au-smokingstatus-intro.md
pages/_includes/profiles.md
resources/au-smokingstatus.xml
resources/ig.xml

Completes the set of changes needed to be a complete profile at DRAFT 0 including copyright and other metadata, meaningful descriptions including shorts, slicenames etc, and terminology.
Addresses issues for Smoking status profile noted in https://github.com/hl7au/au-fhir-base/issues/667.
Also addresses https://jira.hl7australia.com/browse/FHIRIG-160 and https://jira.hl7australia.com/browse/FHIRIG-159

Smoking status QA fixes

---

resources/codesystem-au-location-physical-type.xml
resources/codesystem-au-location-type.xml
resources/codesystem-au-v2-0203.xml
resources/codesystem-au-v2-0360.xml
resources/codesystem-au-v2-0443.xml
resources/codesystem-au-v3-ActCode.xml
resources/codesystem-contact-purpose.xml
resources/codesystem-service-provision-conditions.xml
resources/valueset-accession-number-type.xml
resources/valueset-au-location-physical-type-extended.xml
resources/valueset-au-timezone.xml
resources/valueset-au-v2-0360-extended.xml
resources/valueset-au-v2-0443-extended.xml
resources/valueset-au-v3-ActEncounterCode-extended.xml
resources/valueset-au-v3-ServiceDeliveryLocationRoleType-extended.xml
resources/valueset-contact-purpose.xml
resources/valueset-dva-entitlement.xml
resources/valueset-order-identifier-type.xml

Completed update for Terminology that has gone through ballot and testing now has status=active experimental=false.

Terminology status and experimental flag corrections

---

input/intro-notes/StructureDefinition-au-medlist-intro.md

Replace List.item.entry with List.entry.item and 'guide to this' with 'guide for this'

fix typos in medlist-intro

---

input/intro-notes/StructureDefinition-au-patient-intro.md
input/pagecontent/examples.md
input/pagecontent/guidance.md

The following changes have been made:
- Guidance markdown page - add missing element for business identifiers
- Examples markdown page - fix typo
- AU Base Patient intro - represent SNOMED CT codes and displays using pipe notation (see ballot ticket [FHIRIG-234](https://jira.hl7australia.com/browse/FHIRIG-234))

Ballot: further editorial fixes

---

input/intro-notes/StructureDefinition-au-imagingresult-intro.md
input/resources/au-imagingresult.xml

Changed the profile and updated intro guidance to move the bodysite extension from Observation.extension(bodySite) to the correct position Observation.bodySite.extension(bodySite).
Closes https://github.com/hl7au/au-fhir-base/issues/788

AU Base Diagnostic Imaging Result: moved bodysite extension to Observation.bodySite

---

input/resources/structuredefinition-identifier-routability.xml

Applied AU Base conventions to the invariant inv-routability-preference key, so that it becomes inv-idrout-0.
Fixes #804.

Applied AU Base conventions to the invariant key

---

input/ig.xml

Change IG version number following the 4.1.2-preview snapshot release. Version number changed to 4.1.3.

Change IG version number following the 4.1.2-preview snapshot release

---

input/pagecontent/changes.md

Missed updating Change Log in https://github.com/hl7au/au-fhir-base/pull/812 for changed made to Patient resource to fix the technical issue with genderIdentity binding. This PR adds missing entries.
Related to #815.

Add Change Log entry for Patient genderIdentity changes

---

readme.md

Jira issue tracker link was broken, replaced with a link to AU Base filter.

Fix Jira issue tracker link

---

input/resources/structuredefinition-individual-recordedSexOrGender.xml

In [Person Recorded Sex Or Gender ](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-individual-recordedSexOrGender.html), removed slicing from the [extension:sourceDocument](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-individual-recordedSexOrGender-definitions.html#diff_Extension.extension:sourceDocument) value and replaced with the type choice.

Removed slicing from sourceDocument	datatype

---

input/examples/practitioner-example-sex-and-gender.xml

Fix code system value from 
`<system` value="http://terminology.hl7.org.au/CodeSystem/au-recorded-sex-or-gender-type"/>`
to 
`<system value="http://terminology.hl7.org.au/CodeSystem/rsg-type"/>`
in practitioner-example-sex-and-gender. 
This change was missed in #838.

Fix code system value in practitioner-example-sex-and-gender

---

input/resources/au-patient.xml
input/resources/au-practitioner.xml
input/resources/au-relatedperson.xml

This PR addresses https://jira.hl7.org/browse/FHIR-46176. 
- Updated invariant expressions related to genderIdentity and individualPronouns in AU Base Patient, AU Base RelatedPerson and AU Base Practitioner:
- added missing structure
- added function .all() to apply the condition to each instance of the extension
- Updated invariant expressions related to recordedSexOrGender in AU Base Patient, AU Base RelatedPerson and AU Base Practitioner:
- removed empty check 
- added function .all() to apply the condition to each instance of the extension

Gender Identity, Individual Pronouns and RSG FHIRPath expression fixes 

---

input/examples/practitioner-example-sex-and-gender.xml
input/resources/codesystem-rsg-type.xml

This PR partially addresses [FHIR-46428](https://jira.hl7.org/browse/FHIR-46428) Recorded Sex or Gender type should not be populated with source values:
- changed AU rsg type code system as per JIRA
- updated Practitioner sex-gender example (only example to use the AU rsg type code system)
NOTE: The guidance part of FHIR-46428 will be addressed in a separate PR that will handle the AU Base sex & gender guidance changes.

Fixes for FHIR-46428: changed codesystem & example

---

input/pagecontent/changes.md
input/resources/au-coverage.xml

Fix for [FHIR-47191](https://jira.hl7.org/browse/FHIR-47191)
* Add AU Pensioner Concession Card Number, AU Commonwealth Seniors Health Card Number, AU Health Care Card Number to AU Base Coverage.identifier.
* Change log entry

Add new identifier profiles to Coverage.identifier (FHIR-47191)

---

input/pagecontent/changes.md
input/resources/valueset-au-v3-ActEncounterCode-extended.xml

See [FHIR-47120](https://jira.hl7.org/browse/FHIR-47120) 
Removed PHONE, VIDEO, EMAIL, SMS from [ActEncounterCode - AU Extended](http://terminology.hl7.org.au/ValueSet/v3-ActEncounterCode-extended) as they are subtypes of Virtual Encounter.

 ActEncounterCode AU Extended valueset removal of Virtual Subtypes

---

input/pagecontent/changes.md
input/resources/au-diagnosticresult.xml

Changes for [FHIR-48632](https://jira.hl7.org/browse/FHIR-48632).
Changes include: 
- removed type constraints in AU Base Diagnostic Result
- updated change log

Remove Observation.effective[x] type constraint in AU Base Diagnostic Result (FHIR-48632)

---

input/pagecontent/changes.md
input/pagecontent/terminology.md

Fix for [FHIR-47151](https://jira.hl7.org/browse/FHIR-47151)
- Updated intro text for concept map section of [terminology page](https://build.fhir.org/ig/hl7au/au-fhir-base/terminology.html#concept-maps)

FHIR-47151 Concept Maps subsection needs updating

---

input/ignoreWarnings.txt

ignoreWarnings message syntax fix for https://github.com/hl7au/au-fhir-base/issues/887
Fix for [FHIR-47148](https://jira.hl7.org/browse/FHIR-47148) & [FHIR-47149](https://jira.hl7.org/browse/FHIR-47149)

Fix annotation for #887 (FHIR-47148 & FHIR-47149)

---

input/pagecontent/changes.md

Changes: 
1. The change log links to artefacts in the 4.2.2-ballot release changed to be versioned links to 4.2.2-ballot artefacts.
2. The change log links to artefacts in the 4.1.0 release changed to be versioned links to 4.1.0 artefacts.

Change log links for 4.2.2-ballot & 4.1.0 to go to the version (Github #934)

---

input/intro-notes/StructureDefinition-au-immunization-intro.md
input/pagecontent/changes.md
input/resources/au-immunization.xml
input/resources/au-servicerequest.xml
input/resources/structuredefinition-vaccine-serial-number.xml

Raise AU Base ServiceRequest and Vaccine Vial Serial Number Extension to AFMM1 plus agreed usage of Vaccine Vial Serial Number in AU Base Immunization
Changes as per issues:
[FHIR-49936 AU Base Vaccine Vial Serial Number Extension should be AFMM1](https://jira.hl7.org/browse/FHIR-49936) 
[FHIR-49935 AU Base Service Request should be at AFMM1](https://jira.hl7.org/browse/FHIR-49935)
[FHIR-46317 Add vaccine serial number to AU Base Immunization](https://jira.hl7.org/browse/FHIR-46317)

AFMM update changes (FHIR-49936, FHIR-49935, FHIR-46317)

---

input/resources/au-diagnosticrequest.xml
input/resources/structuredefinition-encounter-description.xml

This PR eliminates QA Report errors by moving the standards-status-reason extension:
> The extension http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status-reason is not allowed to be used at this point (allowed = x:http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status; this element is [StructureDefinition, http://hl7.org.au/fhir/StructureDefinition/encounter-description])
Changes in:
- Encounter Description
- AU Base Diagnostic Request

Refactor invalid use of structuredefinition-standards-status-reason extension from encounter-description and au-diagnosticrequest

---

input/pagecontent/terminology.md

QA Fix - https://github.com/hl7au/au-fhir-base/issues/975
- remove duplicate row "Jurisdiction ValueSet - AU Extended"
- reset value set table to alphabetical order.

QA Fix - Removed duplicate jurisdiction row 

---

input/pagecontent/terminology.md

QA fix
A simple fix for the incorrect hyperlink for the METeOR Person Gender 635994 to HL7 FHIR AdministrativeGender Concept Map. 
The correct URL is: https://healthterminologies.gov.au/fhir/ConceptMap/meteor-person-gender-635994-to-fhir-administrativegender-1, as suggested by Attila Edelenyi from NCTS.

QA fix url for METeOR Person Gender 635994 to HL7 FHIR AdministrativeGender

---

input/resources/structuredefinition-subsidised-concurrent-supply.xml

QA Change to [Subsidised Concurrent Supply ](http://hl7.org.au/fhir/StructureDefinition/subsidised-concurrent-supply) to fix broken URL link to PBS notes section [1.3 Supplying Medicines](https://www.pbs.gov.au/info/healthpro/explanatory-notes/section1/Section-1-3-Explanatory-Notes).

Fix URL for dispense link to PBS in Subsidised Concurrent Supply extension

---

input/pagecontent/changes.md
input/resources/au-pi.xml
input/resources/au-timezone-usage.xml
input/resources/structuredefinition-medication-strength.xml
input/resources/valueset-au-coverage-type-extended.xml
readme.md

Fixes [FHIR-51347](https://jira.hl7.org/browse/FHIR-51347) AFMM1 to publish in the upcoming ballot snapshot:
- Datatype Profile: AU Patient Internal Identifier
- Profile of Extension: Australian Time Zone Usage
- ValueSet: Coverage Type and Self-Pay Codes - AU Extended
- Extension: Medication Strength (Extension)
Change Log convention change so that artefacts marked as AFMM 1 are added as 'new' in this release. Applies to:
- AU Base Service Request
- Vaccine Vial Serial Number extension
- Medication Strength extension

FHIR-51347 - AFMM 1 + Change Log Convention Change
